In [1]:
import pandas as pd
import numpy as np


In [5]:
def leer_datos(dfnew):

    

    E = dfnew.iloc[:, 0]         # Energia de Activación (eV).
    s = dfnew.iloc[:, 1]         # Factor de Frecuencia (s-1).
    # Concentracion de electrones atrapados en las trampas (cm-3).
    n = dfnew.iloc[:, 2]
    # Numero de posiciones acesibles por los electrnes de la BC a la Trampa (cm-3).
    N = dfnew.iloc[:, 3]
    # Coeficiente de Probabilidad de atrapamiento de electrones de a trampa (cm+3·s-1).
    A = dfnew.iloc[:, 4]
    # Coeficiente de probabilidad de recombinacion e-h Radiativa (cm+3·s-1).
    Amn_R = dfnew.iloc[0:1, 5]
    # Coeficiente de probabilidad de recombinacion e-h No Radiativa (cm+3·s-1).
    Amn_NR = dfnew.iloc[0:1, 6]
    # Coeficiente de Probabilidad de atrapamiento de huecos de la BV al Centro de Recombinacion Radiativo (cm+3·s-1).
    A_R = dfnew.iloc[0:1, 7]
    # Coeficiente de Probabilidad de atrapamiento de huecos de la BV al Centro de Recombinacion No Radiativo (cm+3·s-1).
    A_NR = dfnew.iloc[0:1, 8]
    # Numero de posiciones acesibles huecos de la BV al Centro de Recombinacion Radiativo (cm-3).
    M_R = dfnew.iloc[0:1, 9]
    # Numero de posiciones acesibles huecos de la BV al Centro de Recombinacion No Radiativo (cm-3).
    M_NR = dfnew.iloc[0:1, 10]
    # Concentracion de h atrapados en el centro de recombonacion radiativo (cm-3).
    m_R = dfnew.iloc[0:1, 11]
    # Concentracion de h atrapados en el centro de recombonacion no radiativo (cm-3).
    m_NR = dfnew.iloc[0:1, 12]
    f = dfnew.iloc[0:1, 13]     # Factor de generacion de pares e-h (cm-3·s-1).
    # Concentración de electrones libres en la banda de conduccion (cm-3).
    n_c = dfnew.iloc[0:1, 14]
    # Concentración de huecos libres en la banda de Valencia (cm-3).
    n_h = dfnew.iloc[0:1, 15]


    E = E.to_numpy()
    s = s.to_numpy()
    n = n.to_numpy()
    N = N.to_numpy()
    A = A.to_numpy()
    Amn_R = Amn_R.to_numpy()
    Amn_NR = Amn_NR.to_numpy()
    A_R = A_R.to_numpy()
    A_NR = A_NR.to_numpy()
    M_R = M_R.to_numpy()
    M_NR = M_NR.to_numpy()
    m_R = m_R.to_numpy()
    m_NR = m_NR.to_numpy()
    f = f.to_numpy()
    n_c = n_c.to_numpy()
    n_h = n_h.to_numpy()
    return E,s,n,N,A,Amn_R,Amn_NR, A_R,A_NR,M_R,m_R,m_NR,f,n_c,n_h

In [6]:
datos=pd.read_excel('datos/antiguo/Modeladisimo2.xlsx')
leer_datos(datos)

(array([1.2 , 1.15]),
 array([  200000000000000, 17000000000000000], dtype=int64),
 array([0, 0], dtype=int64),
 array([10000000000, 10000000000], dtype=int64),
 array([1.e-08, 1.e-08]),
 array([1.e-08]),
 array([1.e-08]),
 array([1.e-11]),
 array([1.e-11]),
 array([1.e+09]),
 array([0.]),
 array([0.]),
 array([1000000.]),
 array([0.]),
 array([0.]))